struct_cpn = {
    "437" : "United States",
    "850" : "Multilingual",
    "860" : "Portugal",
    "863" : "Canada-French",
    "865" : "Nordic"
    }

struct_dfc = {
    "STL25.01" : "25fps",
    "STL30.01" : "30fps"
    }

struct_dsc = ["Open subtitling","Level-1 teletext","Level-2 teletext"]

struct_cct = ["Latin","Cyrillic","Arabic","Greek","Hebrew"]

struct_lc = [
    "Unknown","Albanian","Breton","Catalan","Croatian","Welsh","Czech","Danish","German","English","Spanish","Esperanto","Estonian","Basque","Faroese","French","Frisian","Irish","Gaelic","Gaelic","Icelandic","Italian",
    "Lappish","Latin","Latvian","Luxembourgian","Lithuanian","Hungarian","Maltese","Dutch","Norwegian","Occitan","Polish","Portugese","Romanian","Romansh","Serbian","Slovak","Slovenian","Finnish","Swedish","Turkish","Flemish","Wallon",
    "","","","","","","","","","","","","","","","","","","","","","","","","","Zulu","Vietnamese","Uzbek","Urdu","Ukrainian","Thai","Telugu","Tatar","Tamil","Tadzhik","Swahili","Sranan Tongo","Somali","Sinhalese","Shona",
    "Serbo-croat","Ruthenian","Russian","Quechua","Pushtu","Punjabi","Persian","Papamiento","Oriya","Nepali","Ndebele","Marathi","Moldavian","Malaysian","Malagasay","Macedonian","Laotian","Korean","Khmer","Kazakh","Kannada","Japanese",
    "Indonesian","Hindi","Hebrew","Hausa","Gurani","Gujurati","Greek","Georgian","Fulani","Dari","Churash","Chinese","Burmese","Bulgarian","Bengali","Bielorussian","Bambora","Azerbaijani","Assamese","Armenian","Arabic","Amharic"
    ]

struct_tcs = ["Not intended for use", "Intended for use"]

struct_cs = ["Not part of a set", "First part of a set", "Intermediate part of a set", "Last part of a set"]

struct_jc = ["unchanged presentation", "left-justified", "centred", "right-justified"]

struct_cf = ["Text is subtitle", "Text is comment"]

struct_iso_6937_2 = {
    "00" : "[Alpha Black]",
    "01" : "[Alpha Red]",
    "02" : "[Alpha Green]",
    "03" : "[Alpha Yellow]",
    "04" : "[Alpha Blue]",
    "05" : "[Alpha Magenta]",
    "06" : "[Alpha Cyn]",
    "07" : "[Alpha White]",
    "08" : "[Flash]",
    "09" : "[Steady]",
    "0A" : "[End Box]",
    "0B" : "[Start Box]",
    "0C" : "[Normal Height]",
    "0D" : "[Double Height]",
    "0E" : "[Double Width]",
    "0F" : "[Double Size]",

    "10" : "[Mosaic Black]",
    "11" : "[Mosaic Red]",
    "12" : "[Mosaic Green]",
    "13" : "[Mosaic Yellow]",
    "14" : "[Mosaic Blue]",
    "15" : "[Mosaic Magenta]",
    "16" : "[Mosaic Cyn]",
    "17" : "[Mosaic White]",
    "18" : "[Conceal]",
    "19" : "[Contiguous Mosaic]",
    "1A" : "[Separated Mosaic]",
    "1B" : "",
    "1C" : "[Black Background]",
    "1D" : "[New Background]",
    "1E" : "[Hold Mosaic]",
    "1F" : "[Release Mosaic]",

    "20" : " ",
    "21" : "!",
    "22" : "\"",
    "23" : "#",
    "24" : "¤",
    "25" : "%",
    "26" : "&",
    "27" : "'",
    "28" : "(",
    "29" : ")",
    "2A" : "*",
    "2B" : "+",
    "2C" : ",",
    "2D" : "-",
    "2E" : ".",
    "2F" : "/",

    "30" : "0",
    "31" : "1",
    "32" : "2",
    "33" : "3",
    "34" : "4",
    "35" : "5",
    "36" : "6",
    "37" : "7",
    "38" : "8",
    "39" : "9",
    "3A" : ":",
    "3B" : ";",
    "3C" : "<",
    "3D" : "=",
    "3E" : ">",
    "3F" : "?",

    "40" : "@",
    "41" : "A",
    "42" : "B",
    "43" : "C",
    "44" : "D",
    "45" : "E",
    "46" : "F",
    "47" : "G",
    "48" : "H",
    "49" : "I",
    "4A" : "J",
    "4B" : "K",
    "4C" : "L",
    "4D" : "M",
    "4E" : "N",
    "4F" : "O",

    "50" : "P",
    "51" : "Q",
    "52" : "R",
    "53" : "S",
    "54" : "T",
    "55" : "U",
    "56" : "V",
    "57" : "W",
    "58" : "X",
    "59" : "Y",
    "5A" : "Z",
    "5B" : "[",
    "5C" : "\\",
    "5D" : "]",
    "5E" : "^",
    "5F" : "_",

    "60" : "`",
    "61" : "a",
    "62" : "b",
    "63" : "c",
    "64" : "d",
    "65" : "e",
    "66" : "f",
    "67" : "g",
    "68" : "h",
    "69" : "i",
    "6A" : "j",
    "6B" : "k",
    "6C" : "l",
    "6D" : "m",
    "6E" : "n",
    "6F" : "o",

    "70" : "p",
    "71" : "q",
    "72" : "r",
    "73" : "s",
    "74" : "t",
    "75" : "u",
    "76" : "v",
    "77" : "w",
    "78" : "x",
    "79" : "y",
    "7A" : "z",
    "7B" : "{",
    "7C" : "|",
    "7D" : "}",
    "7E" : "~",
    "7F" : "",

    "80" : "[Italics On]",
    "81" : "[Italics Off]",
    "82" : "[Underline On]",
    "83" : "[Underline Off]",
    "84" : "[Boxing On]",
    "85" : "[Boxing Off]",
    "86" : "",
    "87" : "",
    "88" : "",
    "89" : "",
    "8A" : "[CRLF]\r\n",
    "8B" : "",
    "8C" : "",
    "8D" : "",
    "8E" : "",
    "8F" : " ",

    "90" : "",
    "91" : "",
    "92" : "",
    "93" : "",
    "94" : "",
    "95" : "",
    "96" : "",
    "97" : "",
    "98" : "",
    "99" : "",
    "9A" : "",
    "9B" : "",
    "9C" : "",
    "9D" : "",
    "9E" : "",
    "9F" : "",

    "A0" : "NBSP",
    "A1" : "¡",
    "A2" : "¢",
    "A3" : "£",
    "A4" : "$",
    "A5" : "¥",
    "A6" : "",
    "A7" : "§",
    "A8" : "",
    "A9" : "‘",
    "AA" : "“",
    "AB" : "«",
    "AC" : "←",
    "AD" : "↑",
    "AE" : "→",
    "AF" : "↓",

    "B0" : "°",
    "B1" : "±",
    "B2" : "²",
    "B3" : "³",
    "B4" : "×",
    "B5" : "µ",
    "B6" : "¶",
    "B7" : "·",
    "B8" : "÷",
    "B9" : "’",
    "BA" : "”",
    "BB" : "»",
    "BC" : "¼",
    "BD" : "½",
    "BE" : "¾",
    "BF" : "¿",

    "C0" : "",
    "C1" : "`",
    "C2" : "´",
    "C3" : "ˆ",
    "C4" : "~",
    "C5" : "̄¯",
    "C6" : "˘",
    "C7" : "˙",
    "C8" : "¨",
    "C9" : "",
    "CA" : "˚",
    "CB" : "¸",
    "CC" : "_",
    "CD" : "˝",
    "CE" : "˛",
    "CF" : "ˇ",

    "D0" : "―",
    "D1" : "¹",
    "D2" : "®",
    "D3" : "©",
    "D4" : "™",
    "D5" : "♪",
    "D6" : "¬",
    "D7" : "¦",
    "D8" : "",
    "D9" : "",
    "DA" : "",
    "DB" : "",
    "DC" : "⅛",
    "DD" : "⅜",
    "DE" : "⅝",
    "DF" : "⅞",

    "E0" : "Ω",
    "E1" : "Æ",
    "E2" : "Đ",
    "E3" : "ª",
    "E4" : "Ħ",
    "E5" : "",
    "E6" : "Ĳ",
    "E7" : "Ŀ",
    "E8" : "Ł",
    "E9" : "Ø",
    "EA" : "Œ",
    "EB" : "º",
    "EC" : "Þ",
    "ED" : "Ŧ",
    "EE" : "Ŋ",
    "EF" : "ŉ",

    "F0" : "ĸ",
    "F1" : "æ",
    "F2" : "đ",
    "F3" : "ð",
    "F4" : "ħ",
    "F5" : "ı",
    "F6" : "ĳ",
    "F7" : "ŀ",
    "F8" : "ł",
    "F9" : "ø",
    "FA" : "œ",
    "FB" : "ß",
    "FC" : "þ",
    "FD" : "ŧ",
    "FE" : "ŋ",
    "FF" : "SHY",
}